theme = 'everforest_dark'

[editor]
line-number = 'relative'
mouse = true
bufferline = 'always'
scrolloff = 8
cursorline = true
color-modes = true

[editor.whitespace]
render = 'none'

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # "▏", "┆", "┊"
skip-levels = 1

[editor.lsp]
display-signature-help-docs = true
# display-inline-hints = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
'L' = ':buffer-next'
'H' = ':buffer-previous'
A-j = ['extend_to_line_bounds', 'delete_selection', 'paste_after']
A-k = ['extend_to_line_bounds', 'delete_selection', 'move_line_up', 'paste_before']
A-J = ['extend_to_line_bounds', 'yank', 'move_line_up', 'paste_before']
A-K = ['extend_to_line_bounds', 'yank', 'move_line_up', 'paste_before']
C-d = ['half_page_down', 'goto_window_center']
C-u = ['half_page_up', 'goto_window_center']
"{" = ['goto_prev_paragraph', 'collapse_selection']
"}" = ['goto_next_paragraph', 'collapse_selection']

[keys.normal.space]
x = ':buffer-close'
q = ':quit-all'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'

[editor.statusline]
right = ['version-control', 'diagnostics', 'selections', 'position', 'file-encoding']

[editor.file-picker]
hidden = false
