theme = 'catppuccin_frappe'

[editor]
line-number = 'relative'
mouse = true
bufferline = 'always'
scrolloff = 8
cursorline = true
color-modes = true
true-color = true

[editor.whitespace]
render = 'none'

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # "▏", "┆", "┊"
skip-levels = 1

[editor.lsp]
display-signature-help-docs = true
display-inlay-hints = true
# inline-diagnostics = {max-warp = 1}

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
tab = "goto_next_function"
S-tab = "goto_prev_function"
L = 'goto_next_buffer'
H = 'goto_previous_buffer'
A-j = ['extend_to_line_bounds', 'delete_selection', 'paste_after']
A-k = ['extend_to_line_bounds', 'delete_selection', 'move_line_up', 'paste_before']
A-J = ['extend_to_line_bounds', 'yank', 'move_line_up', 'paste_before']
A-K = ['extend_to_line_bounds', 'yank', 'move_line_up', 'paste_before']
C-d = ['half_page_down', 'goto_window_center']
C-u = ['half_page_up', 'goto_window_center']
"{" = ['goto_prev_paragraph', 'collapse_selection']
"}" = ['goto_next_paragraph', 'collapse_selection']
x = "extend_line"
D = ["ensure_selections_forward", "extend_to_line_end"]
X = ["goto_first_nonwhitespace", "extend_to_line_end"]
"'" = "goto_word"

[keys.select]
";" = ["collapse_selection", "normal_mode"]

[keys.insert]
C-h = ['move_char_left']
C-l = ['move_char_right']
C-j = ['move_line_down']
C-k = ['move_line_up']

[keys.normal.space]
c = ':buffer-close'
q = ':quit-all'

[editor.cursor-shape]
insert = 'bar'
normal = 'block'

[editor.statusline]
right = ['version-control', 'diagnostics', 'selections', 'position', 'file-encoding']

[editor.file-picker]
hidden = false
